GameMsgDef = {}

GameMsgDef.ID_UPDAGE_HEAD_IMG = MsgDef.GAME_MSG_START + 1
GameMsgDef.ID_MOREGAME_DOWNLOADED_IMG = MsgDef.GAME_MSG_START + 2

-- Tourney 数据更新了
GameMsgDef.ID_CUSTOM_TOURNEY_CHANGE = MsgDef.GAME_MSG_START + 3
GameMsgDef.ID_LOGIN_RESULT = MsgDef.GAME_MSG_START + 4

--公告&私信未读状态变化
GameMsgDef.ID_NOTE_MSG_READ_STATE_CHANGE = MsgDef.GAME_MSG_START + 6
GameMsgDef.ID_ROAR_MSG_UPDATE_CHANGE = MsgDef.GAME_MSG_START + 7

--view切换消息
GameMsgDef.ID_MATCH_VIEW_CHANGE = MsgDef.GAME_MSG_START + 8

--G10086 SDK状态变化
GameMsgDef.ID_G10086_SDK_STATE_CHANGE = MsgDef.GAME_MSG_START + 9

return GameMsgDef